from app.services.adk_service import run_adk_agent


async def generate_script(prompt: str, project) -> dict:
    instruction = "You are a professional screenwriter assistant."
    full_prompt = f"""
Project: "{project.title}" | Genre: {project.genre or 'unspecified'} | Logline: {project.logline or 'none'}

Task: {prompt}

Respond in this exact format:
SCRIPT:
<full script content here>

SCENE_BREAKDOWN:
<JSON array of scene objects with keys: scene_number, location, time, description>

CHARACTERS:
<JSON array of character objects with keys: name, description, arc>

NOTES:
<brief director notes and suggestions>
"""
    text = await run_adk_agent(name="screenwriter_agent", instruction=instruction, prompt=full_prompt)

    def extract(marker_start, marker_end):
        try:
            start = text.index(marker_start) + len(marker_start)
            end = text.index(marker_end, start) if marker_end in text[start:] else len(text)
            return text[start:end].strip()
        except ValueError:
            return None

    content = extract("SCRIPT:\n", "\nSCENE_BREAKDOWN:")
    scene_breakdown = extract("SCENE_BREAKDOWN:\n", "\nCHARACTERS:")
    characters = extract("CHARACTERS:\n", "\nNOTES:")
    ai_notes = extract("NOTES:\n", "\n\n\n")

    return {
        "content": content or text,
        "scene_breakdown": scene_breakdown,
        "characters": characters,
        "ai_notes": ai_notes or "Generated by Groq via Google ADK",
    }
